version: "3.8"

services:
  moki-front:
    build:
      context: ./Frontend
      args:
        BACKEND_URL: ${BACKEND_URL}
    container_name: moki-front
    ports:
      - "${FRONTEND_PORT}:80"
  moki-back:
    build:
      context: "./Backend"
    container_name: moki-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_INNER_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: "Asia/Seoul"
    depends_on:
      - moki-db
  moki-mlops:
    build:
      context: "./MLOps"
    container_name: moki-mlops
    environment:
      TZ: "Asia/Seoul"
  moki-db:
    image: mysql:8
    container_name: moki-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PW}
      MYSQL_DATABASE: moki
    ports:
      - "${MYSQL_PORT}:${MYSQL_INNER_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
